fix: add check for golint errors

diff --git a/.github/workflows/ci_pr.yaml b/.github/workflows/ci_pr.yaml
--- a/.github/workflows/ci_pr.yaml
+++ b/.github/workflows/ci_pr.yaml
@@ -47,4 +47,8 @@ jobs:
       timeout-minutes: 20
       run: |
         golint ./... > golint.err
-        [ -s golint.err ]
+        if ! grep -q '"./..." matched no packages' "golint.err"; then
+          echo '[✘] Some .go files are not properly formatted. Check for lint errors using (golint ./...)'
+          cat golint.err
+          exit 1
+        fi
